services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 
    container_name: 
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: 
    restart: unless-stopped
    environment:
      POSTGRES_DB: aisitedb
      POSTGRES_USER: aisitedb
      POSTGRES_PASSWORD: aisitedb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
